server:
  port: 5000
  api-prefix: /api
  http2:
    enabled: true

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://192.168.1.238:3306/url-shortener?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

