spring:
  main:
    banner-mode: off
  h2:
    console:
      enable: false
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ab;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  flyway:
    enabled: false

server:
  api-prefix: /api
  http2:
    enabled: true

secrets:
  publicKey: "secret"
  privateKey: "secret"