apiVersion: v1
kind: Service
metadata:
        name: url-shortener-service
spec:
        type: LoadBalancer
        selector:
                app: url-web
        ports:
              - port: 5000
                targetPort: 5000
